# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following lines activate a set of recommended lints.
include:
  - package:flutter_lints/flutter.yaml
  - package:lint/strict.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - lib/src/styles/lichess_icons.dart
    - lib/src/styles/social_icons.dart
    - lib/firebase_options.dart
    - lib/l10n/*.dart
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint

formatter:
  page_width: 100

linter:
  rules:
    require_trailing_commas: false
    prefer_single_quotes: true
    always_use_package_imports: true
    avoid_redundant_argument_values: false
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: false
