const federationIdToName = {
  'AFG': 'Afghanistan',
  'AHO': 'Netherlands Antilles',
  'ALB': 'Albania',
  'ALG': 'Algeria',
  'AND': 'Andorra',
  'ANG': 'Angola',
  'ANT': 'Antigua and Barbuda',
  'ARG': 'Argentina',
  'ARM': 'Armenia',
  'ARU': 'Aruba',
  'AUS': 'Australia',
  'AUT': 'Austria',
  'AZE': 'Azerbaijan',
  'BAH': 'Bahamas',
  'BAN': 'Bangladesh',
  'BAR': 'Barbados',
  'BDI': 'Burundi',
  'BEL': 'Belgium',
  'BER': 'Bermuda',
  'BHU': 'Bhutan',
  'BIH': 'Bosnia & Herzegovina',
  'BIZ': 'Belize',
  'BLR': 'Belarus',
  'BOL': 'Bolivia',
  'BOT': 'Botswana',
  'BRA': 'Brazil',
  'BRN': 'Bahrain',
  'BRU': 'Brunei Darussalam',
  'BUL': 'Bulgaria',
  'BUR': 'Burkina Faso',
  'CAF': 'Central African Republic',
  'CAM': 'Cambodia',
  'CAN': 'Canada',
  'CAY': 'Cayman Islands',
  'CHA': 'Chad',
  'CHI': 'Chile',
  'CHN': 'China',
  'CIV': 'Cote d’Ivoire',
  'CMR': 'Cameroon',
  'COD': 'Democratic Republic of the Congo',
  'COL': 'Colombia',
  'COM': 'Comoros Islands',
  'CPV': 'Cape Verde',
  'CRC': 'Costa Rica',
  'CRO': 'Croatia',
  'CUB': 'Cuba',
  'CUR': 'Curacao',
  'CYP': 'Cyprus',
  'CZE': 'Czech Republic',
  'DEN': 'Denmark',
  'DJI': 'Djibouti',
  'DMA': 'Dominica',
  'DOM': 'Dominican Republic',
  'ECU': 'Ecuador',
  'EGY': 'Egypt',
  'ENG': 'England',
  'ERI': 'Eritrea',
  'ESA': 'El Salvador',
  'ESP': 'Spain',
  'EST': 'Estonia',
  'ETH': 'Ethiopia',
  'FAI': 'Faroe Islands',
  'FID': 'FIDE',
  'FIJ': 'Fiji',
  'FIN': 'Finland',
  'FRA': 'France',
  'GAB': 'Gabon',
  'GAM': 'Gambia',
  'GCI': 'Guernsey',
  'GEO': 'Georgia',
  'GEQ': 'Equatorial Guinea',
  'GER': 'Germany',
  'GHA': 'Ghana',
  'GRE': 'Greece',
  'GRN': 'Grenada',
  'GUA': 'Guatemala',
  'GUM': 'Guam',
  'GUY': 'Guyana',
  'HAI': 'Haiti',
  'HKG': 'Hong Kong, China',
  'HON': 'Honduras',
  'HUN': 'Hungary',
  'INA': 'Indonesia',
  'IND': 'India',
  'IOM': 'Isle of Man',
  'IRI': 'Iran',
  'IRL': 'Ireland',
  'IRQ': 'Iraq',
  'ISL': 'Iceland',
  'ISR': 'Israel',
  'ISV': 'US Virgin Islands',
  'ITA': 'Italy',
  'IVB': 'British Virgin Islands',
  'JAM': 'Jamaica',
  'JCI': 'Jersey',
  'JOR': 'Jordan',
  'JPN': 'Japan',
  'KAZ': 'Kazakhstan',
  'KEN': 'Kenya',
  'KGZ': 'Kyrgyzstan',
  'KIR': 'Kiribati',
  'KOR': 'South Korea',
  'KOS': 'Kosovo *',
  'KSA': 'Saudi Arabia',
  'KUW': 'Kuwait',
  'LAO': 'Laos',
  'LAT': 'Latvia',
  'LBA': 'Libya',
  'LBN': 'Lebanon',
  'LBR': 'Liberia',
  'LCA': 'Saint Lucia',
  'LES': 'Lesotho',
  'LIE': 'Liechtenstein',
  'LTU': 'Lithuania',
  'LUX': 'Luxembourg',
  'MAC': 'Macau',
  'MAD': 'Madagascar',
  'MAR': 'Morocco',
  'MAS': 'Malaysia',
  'MAW': 'Malawi',
  'MDA': 'Moldova',
  'MDV': 'Maldives',
  'MEX': 'Mexico',
  'MGL': 'Mongolia',
  'MHL': 'Marshall Islands',
  'MKD': 'North Macedonia',
  'MLI': 'Mali',
  'MLT': 'Malta',
  'MNC': 'Monaco',
  'MNE': 'Montenegro',
  'MOZ': 'Mozambique',
  'MRI': 'Mauritius',
  'MTN': 'Mauritania',
  'MYA': 'Myanmar',
  'NAM': 'Namibia',
  'NCA': 'Nicaragua',
  'NED': 'Netherlands',
  'NEP': 'Nepal',
  'NGR': 'Nigeria',
  'NIG': 'Niger',
  'NOR': 'Norway',
  'NRU': 'Nauru',
  'NZL': 'New Zealand',
  'OMA': 'Oman',
  'PAK': 'Pakistan',
  'PAN': 'Panama',
  'PAR': 'Paraguay',
  'PER': 'Peru',
  'PHI': 'Philippines',
  'PLE': 'Palestine',
  'PLW': 'Palau',
  'PNG': 'Papua New Guinea',
  'POL': 'Poland',
  'POR': 'Portugal',
  'PUR': 'Puerto Rico',
  'QAT': 'Qatar',
  'ROU': 'Romania',
  'RSA': 'South Africa',
  'RUS': 'Russia',
  'RWA': 'Rwanda',
  'SCO': 'Scotland',
  'SEN': 'Senegal',
  'SEY': 'Seychelles',
  'SGP': 'Singapore',
  'SKN': 'Saint Kitts and Nevis',
  'SLE': 'Sierra Leone',
  'SLO': 'Slovenia',
  'SMR': 'San Marino',
  'SOL': 'Solomon Islands',
  'SOM': 'Somalia',
  'SRB': 'Serbia',
  'SRI': 'Sri Lanka',
  'SSD': 'South Sudan',
  'STP': 'Sao Tome and Principe',
  'SUD': 'Sudan',
  'SUI': 'Switzerland',
  'SUR': 'Suriname',
  'SVK': 'Slovakia',
  'SWE': 'Sweden',
  'SWZ': 'Eswatini',
  'SYR': 'Syria',
  'TAN': 'Tanzania',
  'TGA': 'Tonga',
  'THA': 'Thailand',
  'TJK': 'Tajikistan',
  'TKM': 'Turkmenistan',
  'TLS': 'Timor-Leste',
  'TOG': 'Togo',
  'TPE': 'Chinese Taipei',
  'TTO': 'Trinidad & Tobago',
  'TUN': 'Tunisia',
  'TUR': 'Turkiye',
  'UAE': 'United Arab Emirates',
  'UGA': 'Uganda',
  'UKR': 'Ukraine',
  'URU': 'Uruguay',
  'USA': 'United States of America',
  'UZB': 'Uzbekistan',
  'VAN': 'Vanuatu',
  'VEN': 'Venezuela',
  'VIE': 'Vietnam',
  'VIN': 'Saint Vincent and the Grenadines',
  'WLS': 'Wales',
  'YEM': 'Yemen',
  'ZAM': 'Zambia',
  'ZIM': 'Zimbabwe',
};
