import 'dart:isolate';

import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:lichess_mobile/src/model/practice/practice_structure.dart';
import 'package:lichess_mobile/src/utils/json.dart';

/// A provider for [PracticeRepository].
final practiceRepositoryProvider = Provider<PracticeRepository>(
  (Ref ref) => PracticeRepository(rootBundle),
  name: 'PracticeRepositoryProvider',
);

/// The practice content, loaded once and kept for the lifetime of the app.
final practiceStructureProvider = FutureProvider<PracticeStructure>(
  (Ref ref) => ref.read(practiceRepositoryProvider).getStructure(),
  name: 'PracticeStructureProvider',
);

/// The practice content, read from the asset embedded in the app.
///
/// Practice is fully offline: the content comes from `assets/practice.json`, generated by
/// `scripts/gen_practice.dart`.
class const PracticeRepository(final AssetBundle _bundle) {
  static const asset = 'assets/practice.json';

  /// Decodes and parses the asset in a background isolate, as it is too big to be done on the UI
  /// isolate without dropping frames on slow devices.
  Future<PracticeStructure> getStructure() async {
    final bytes = await _bundle.load(asset);
    return await Isolate.run(
      () => PracticeStructure.fromJson(
        jsonUtf8Decoder.convert(Uint8List.sublistView(bytes))! as Map<String, dynamic>,
      ),
      debugName: 'Practice structure parsing',
    );
  }
}
