/// Flutter icons LichessIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LichessIcons
///      fonts:
///       - asset: fonts/LichessIcons.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class LichessIcons {
  LichessIcons._();

  static const _kFontFam = 'LichessIcons';
  static const String? _kFontPkg = null;

  // dart format off
  static const IconData patron = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData target = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blitz = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData classical = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bullet = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rapid = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ultrabullet = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData correspondence = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_full_upperright = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_full_lowerright = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData storm = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData horde = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData antichess = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData atom = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData three_check = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData h_square = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData die_six = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData racing_kings = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feather = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData streak = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microscope = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tournament_cup = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cogs = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crown = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lichess = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adjust = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flow_cascade = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radio_tower_lichess = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossed_swords = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_lichess = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData study = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData body_cut = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag = IconData(0xf02b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tags = IconData(0xf02c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData step_backward = IconData(0xf048, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_backward = IconData(0xf049, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_forward = IconData(0xf050, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData step_forward = IconData(0xf051, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_empty = IconData(0xf10c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle = IconData(0xf111, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess = IconData(0xf439, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess_bishop = IconData(0xf43a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess_board = IconData(0xf43c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess_king = IconData(0xf43f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess_knight = IconData(0xf441, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess_pawn = IconData(0xf443, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess_queen = IconData(0xf445, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess_rook = IconData(0xf447, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tools = IconData(0xf7d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
