name: Builds
on: workflow_dispatch

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["appbundle --debug", "ios --no-codesign"]
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Install Flutter
        uses: subosito/flutter-action@v2
      - run: flutter doctor -v

      - name: Checkout mobile code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: flutter pub get

      - name: Code generation
        run: dart run build_runner build

      - run: flutter build ${{ matrix.target }}

      - name: Upload Android AAB
        if: contains(matrix.target, 'appbundle')
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.aab
          path: build/app/outputs/bundle/debug/app-debug.aab

      - name: Upload iOS App
        if: contains(matrix.target, 'ios')
        uses: actions/upload-artifact@v4
        with:
          name: Runner.app
          path: build/ios/iphoneos/Runner.app
