name: Builds
on: workflow_dispatch

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: macos-26
    strategy:
      fail-fast: false
      matrix:
        target: ["appbundle --debug", "ios --no-codesign", "apk --debug"]
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          java-version: 17
          distribution: temurin

      - name: Checkout mobile code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          flutter-version-file: pubspec.yaml
      - run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Code generation
        run: dart run build_runner build

      - run: flutter build ${{ matrix.target }}

      - name: Upload debug APK
        if: matrix.target == 'apk --debug'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: lichess-mobile-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: error
          retention-days: 7
