name: Crowdin mobile source push

on:
  push:
    paths:
        - 'translation/source/mobile.xml'
    branches: [ main ]
  workflow_dispatch:

jobs:
  crowdin-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Crowdin push
        uses: crowdin/github-action@8f01d54f70f1713ee3f09d82c2bbb2daeac28689 # v2.17.1
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          source: translation/source/mobile.xml
          translation: /translation/dest/%file_name%/%locale%.%file_extension%
          crowdin_branch_name: '[lichess-org.mobile] main'
          upload_sources_args: '--preserve-hierarchy'
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
