name: Draft Github Release
on:
  # Enable manual run
  workflow_dispatch:
    inputs:
      version:
        description: "Tag to create (e.g. v0.4.0). Must include 'v' and must match pubspec"
        required: true
        default: "v0.4.0"
        type: string

# Creating a release and its tag writes to the repository.
permissions:
  contents: write

jobs:
  draft-release:
    name: Draft Github release
    runs-on: ubuntu-latest
    steps:
      - name: Draft release with release notes
        id: create_release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64
        with:
          tag_name: ${{ github.event.inputs.version }}
          draft: true
          prerelease: false
          generate_release_notes: true
          # files: lichess-mobile.apk

