name: Draft Github Release
on:
  # Enable manual run
  workflow_dispatch:
    inputs:
      version:
        description: "Tag to create (e.g. v0.4.0). Must include 'v' and must match pubspec"
        required: true
        default: "v0.4.0"
        type: string

# Declare default permissions as read only.
permissions: read-all

jobs:
  draft-release:
    name: Draft Github release
    runs-on: ubuntu-latest
    # needs: create-build
    steps:
      - name: Draft release with release notes
        id: create_release
        uses: softprops/action-gh-release@7b4da11513bf3f43f9999e90eabced41ab8bb048
        with:
          tag_name: ${{ github.event.inputs.version }}
          draft: true
          prerelease: false
          generate_release_notes: true
          # files: lichess-mobile.apk

  # create-build:
  #   name: Create android build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v4
  #       with:
  #         java-version: 17
  #         distribution: temurin

  #     - name: Install Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: stable
  #     - run: flutter doctor -v

  #     - name: Checkout mobile code
  #       uses: actions/checkout@v4

  #     - name: Install dependencies
  #       run: flutter pub get

  #     - name: Code generation
  #       run: dart run build_runner build

  #     - name: Configure Keystore
  #       run: |
  #         echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
  #         echo "storeFile=upload-keystore.jks" >> key.properties
  #         echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
  #         echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
  #         echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
  #       env:
  #         PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
  #         KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
  #         KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
  #         KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
  #       working-directory: android

  #     - run: flutter build -v apk --release

  #     - name: Rename build
  #       run: mv app-release.apk $GITHUB_WORKSPACE/lichess-mobile.apk
  #       working-directory: build/app/outputs/flutter-apk
