name: Upload the F-Droid APK to Github
on:
  push:
    tags:
      - 'v*.*.*.fdroid'

permissions:
  contents: write

jobs:
  github-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mobile code
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin

      - name: Read Flutter version
        run: echo "FLUTTER_VERSION=$(cat flutter-version)" >> $GITHUB_ENV

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Patch Flutter
        run: |
          git -C ${{ env.FLUTTER_ROOT }} apply $GITHUB_WORKSPACE/flutter.patch
          rm ${{ env.FLUTTER_ROOT }}/bin/cache/flutter_tools.snapshot

      - name: Install dependencies
        run: flutter pub get

      - name: Patch dependencies
        run: |
          sed -i 's/-Wl,/-Wl,--build-id=none,/' ~/.pub-cache/hosted/pub.dev/jni-*/src/CMakeLists.txt
          sed -i 's/-Wl,/-Wl,--build-id=none,/' ~/.pub-cache/hosted/pub.dev/multistockfish_chess-*/src/CMakeLists.txt
          sed -i 's/-Wl,/-Wl,--build-id=none,/' ~/.pub-cache/hosted/pub.dev/multistockfish_sf16-*/src/CMakeLists.txt
          sed -i 's/-Wl,/-Wl,--build-id=none,/' ~/.pub-cache/hosted/pub.dev/multistockfish_variant-*/android/CMakeLists.txt
          truncate -s 0 ~/.pub-cache/hosted/pub.dev/webcrypto-*/android/CMakeLists.txt

      - name: Code generation
        run: dart run build_runner build

      - name: Configure Keystore
        run: |
          echo "${{ secrets.FDROID_KEYSTORE_FILE }}" | base64 --decode > app/lichess-fdroid.keystore
          echo "storeFile=lichess-fdroid.keystore" >> key.properties
          echo "keyAlias=${{ secrets.FDROID_KEYSTORE_KEY_ALIAS }}" >> key.properties
          echo "storePassword=${{ secrets.FDROID_KEYSTORE_STORE_PASSWORD }}" >> key.properties
          echo "keyPassword=${{ secrets.FDROID_KEYSTORE_KEY_PASSWORD }}" >> key.properties
        working-directory: android

      - name: Build APKs
        run: |
          flutter build apk --split-per-abi --target-platform="android-x64" --dart-define=cronetHttpNoPlay=true --dart-define=LICHESS_HOST=lichess.org --dart-define=LICHESS_WS_HOST=socket.lichess.org --dart-define=LICHESS_WS_SECRET=wG1OLhUR3CSXdDybqrtIW227QGrtiM3d
          flutter build apk --split-per-abi --target-platform="android-arm" --dart-define=cronetHttpNoPlay=true --dart-define=LICHESS_HOST=lichess.org --dart-define=LICHESS_WS_HOST=socket.lichess.org --dart-define=LICHESS_WS_SECRET=wG1OLhUR3CSXdDybqrtIW227QGrtiM3d
          flutter build apk --split-per-abi --target-platform="android-arm64" --dart-define=cronetHttpNoPlay=true --dart-define=LICHESS_HOST=lichess.org --dart-define=LICHESS_WS_HOST=socket.lichess.org --dart-define=LICHESS_WS_SECRET=wG1OLhUR3CSXdDybqrtIW227QGrtiM3d

      - name: Rename APKs
        run: |
          VERSION_CODE=$(yq eval '.version' pubspec.yaml | cut -d '+' -f 2)
          BASE=$((10#$VERSION_CODE * 100))
          declare -A ARCH_MAP=(["x86_64"]=1 ["armeabi-v7a"]=2 ["arm64-v8a"]=3)
          for ARCH in "${!ARCH_MAP[@]}"; do
            mv build/app/outputs/flutter-apk/app-${ARCH}-release.apk build/app/outputs/flutter-apk/$((BASE + ARCH_MAP[$ARCH]))-${ARCH}-fdroid.apk
          done

      - name: Determine release tag
        run: |
          TRIGGER_TAG=${GITHUB_REF#refs/tags/}
          RELEASE_TAG=${TRIGGER_TAG%.fdroid}
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

      - name: Upload APKs
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: build/app/outputs/flutter-apk/*-fdroid.apk
